<form class="formulaires" action="inscription_traitement.php" method="post">
    <h2 class="text-center">Inscription</h2> 
    <fieldset>   
    <div>
        <input type="text" name="pseudo" placeholder="Pseudo" required="required" autocomplete="off">
    </div>
    <div>
        <input type="email" name="email" placeholder="Email" required="required" autocomplete="off">
    </div>
    <div>
        <input type="password" name="password" placeholder="Mot de passe" required="required" autocomplete="off">
    </div>
    <div>
        <input type="password" name="password_retype" placeholder="Re-tapez le mot de passe" required="required" autocomplete="off">
    </div>
    <div>
        <button type="submit">Inscription</button>
    </div>
    </fieldset>   
</form>