<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<main>
    <div>
        <h1>Bonjour <?php echo $_SESSION['user']; ?> !</h1>
        <a class="text_align" href="logout.php">Déconnexion</a>
    </div>
    <nav>    
        <a href="index">retour</a>
    </nav> 
</main>  
</body>
</html>