<form class="formulaires" action="login.php" method="post">
    <fieldset>
        <div>
            <label for="text">Email</label>
            <input type="email" name="email" required="required">
        </div>
        <div>
            <label for="password">Mot de passe</label>
            <input type="password" name="password" required="required">
        </div>
        <button type="submit">Se connecter</button>
    </fieldset>
</form>
<h2 class="middle"><a href="inscription.php">Inscription</a></h2>