<main class="container">
    <h2 class="center">Affichage de la base de données avec suppression et modification, si la personne est connecté</h2>
    <table>
        <tr>
            <td>nom</td>
            <td>mail</td>
        </tr>
    <?php
    foreach ($users as $user): ?>
        <tr>
            <td><?= $user['nom']; ?></td>
            <td><?= $user['mail']; ?><a href="delete_post.php?id=<?= $user['idUser'] ?>">X</a><a href="edit_post.php?id=<?= $user['idUser'] ?>"><i class="fas fa-cog"></i></a></td>   
        </tr>
    <?php endforeach ?>    
    </table>
    <h2 class="center">PokeDex</h2>
    <p>Cliquez sur le bouton pour former aléatoirement votre équipe de 6, certaine image des pokemons n'apparaitront pas du fait d'une indisponibilité sur l'API</p>
    <div>
        <input type="button" id="random" value="Random Team">
    </div>
    <div id="poke_container" class="poke-container"></div>
</main>